wandb_version: 1

arch:
  desc: null
  value: InceptionV4
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1691945946.374175
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.15.8
      8:
      - 1
      - 5
