wandb_version: 1

batch_size:
  desc: null
  value: 176
flip_left_right:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.8
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1691782276.238646
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 7
      - 16
      - 23
      - 38
      4: 3.8.10
      5: 0.15.8
      8:
      - 1
      - 5
    m:
    - 1: epoch/epoch
      6:
      - 3
    - 1: epoch/loss
      5: 1
      6:
      - 1
    - 1: epoch/prec
      5: 1
      6:
      - 1
    - 1: epoch/rec
      5: 1
      6:
      - 1
    - 1: epoch/val_loss
      5: 1
      6:
      - 1
    - 1: epoch/val_prec
      5: 1
      6:
      - 1
    - 1: epoch/val_rec
      5: 1
      6:
      - 1
    - 1: epoch/learning_rate
      5: 1
      6:
      - 1
