wandb_version: 1

Data aug:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1692593658.014515
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.13.4
      8:
      - 1
      - 5
arch:
  desc: null
  value: InceptionV4
batch_size:
  desc: null
  value: 328
classes:
  desc: null
  value: 30
epochs:
  desc: null
  value: 50
learning rate:
  desc: null
  value: 0.001
loss_function:
  desc: null
  value: CrossEntropyLoss()
momentum:
  desc: null
  value: 0.5
optimizer:
  desc: null
  value: SGD
